### PR TITLE
Re-run `definitions:generateMavlink` task

### PR DESCRIPTION
**Pull request by rowden-jon**
Apologies for the massive diff, but I just tried running `gradle definitions:generateMavlink` on the latest versions of [the Mavlink XML definition files from the official repo](https://github.com/mavlink/mavlink/tree/master/message_definitions/v1.0). Seems there have been a few changes since this was last run!

From a glance, the changes include (in roughly-descending order of impact):
- new/renamed fields
- new enums/types
- new/renamed enum entries
- sub-dialect changes for some of the dialects
- `SpeedType` moved from `ardupilotmega` to `common` dialect
- some classes have `@WorkInProgress` annotations removed
- extra comments and typo fixes

Also bear in mind that I've not actually tested any of this on any actual drones - just thought it might be useful.

Might be useful to have this kind of thing automated to help with keeping on top of changes. I think Github Actions allows cronjobs, I could set that up if you think it's useful :+1:

### CODE REVIEW

**Comment by divyanshupundir** [comment]
@rowden-jon good PRs like these are wholeheartedly welcome. I'll do a quick review and test. I'll create a release soon.

> Might be useful to have this kind of thing automated to help with keeping on top of changes. I think Github Actions allows cronjobs, I could set that up if you think it's useful 👍

That would be a massive help!

I too want to set up automated workflows and start work on the multiplatform part (maybe even some core MAVLink microservices), but I have been unable to find time for those things for a while.

**Comment by divyanshupundir** [comment]
I hope you generated these using the latest stable MAVLink definitions?

Also, I am thinking of setting up the workflow in a way that takes the input as the GitHub URL of the files. That would remove the need to maintain the MAVlink submodule.

**Comment by rowden-jon** [comment]
> I hope you generated these using the latest stable MAVLink definitions?

Latest commit of the repo on main. They don't have releases on there, and the latest tag was in 2019 so that's all we have to define as "stable". That being said, their CI has been failing for the past few commits - apparently only on some Node.JS tests.

> Also, I am thinking of setting up the workflow in a way that takes the input as the GitHub URL of the files. That would remove the need to maintain the MAVlink submodule.

Agreed - can use this to get the latest commit in the definitions folder. Would be a nifty pre-check to see whether the definitions have changed before we clone.

**Comment by divyanshupundir** [comment]
Okay. Can you please also check out the mavlink submodule to the latest master commit and push that change as well?

**Comment by rowden-jon** [comment]
Didn't even realise that was a submodule! Sorted :white_check_mark:

**Comment by divyanshupundir** [comment]
Thanks! Just give me a couple of days.

**Review by divyanshupundir — APPROVED** [review]
Looks good.

**Pull request merged**
